# Generated by Django 5.1.15 on 2026-04-10 02:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('issue_type', models.CharField(choices=[('flat_repair', 'Flat Repair'), ('locked_out', 'Roadside - Locked Out'), ('no_fuel', 'Roadside - No Fuel'), ('jumpstart', 'Roadside - Battery Jumpstart'), ('tire_replacement', 'Tire Replacement / Installation'), ('emergency', 'Emergency')], max_length=50)),
                ('tire_size', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('assigned', 'Technician Assigned'), ('en_route', 'En Route'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('status_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
