# Generated by Django 5.1.15 on 2026-04-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=999, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=999, null=True),
        ),
    ]
